service: base-project-serverless

useDotenv: true
configValidationMode: error
variablesResolutionMode: 20210326

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  lambdaHashingVersion: 20201221
  environment:
    LAMBDA: true
    NODE_ENV: ${env:NODE_ENV}
    MONGODB_URL: ${ssm:MONGODB_URL}
  apiGateway:
    usagePlan:
      quota:
        limit: 1000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 5
        rateLimit: 5

package:
  excludeDevDependencies: true
  patterns:
    - "!**/**"
    - .env
    - dist/index.js
    - serverless.yml
    - package.json
    - yarn.lock

functions:
  index:
    handler: dist/index.handler
    provisionedConcurrency: 1
    events:
      - http:
          cors: true
          path: "/"
          method: post
      - http:
          cors: true
          path: "{proxy+}"
          method: post
