service: base-project-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/main.handler
    events:
      - http:
          cors: true
          path: "/"
          method: any
      - http:
          cors: true
          path: "{proxy+}"
          method: any
